<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="OPTIMUSPRIME" failures="1" tests="6" name="Default test" time="0.149" errors="0" timestamp="09 Jun 2023 17:02:23 GMT">
  <testcase classname="com.testNG.Program.Hard_Dependency_TestNG" name="lunchApplication" time="0.028">
    <failure type="java.lang.AssertionError" message="Titles are Same expected [Pag Title] but found [Page Title]">
      <![CDATA[java.lang.AssertionError: Titles are Same expected [Pag Title] but found [Page Title]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.testNG.Program.Hard_Dependency_TestNG.lunchApplication(Hard_Dependency_TestNG.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- lunchApplication -->
  <testcase classname="com.testNG.Program.Hard_Dependency_TestNG" name="loginUser" time="0.0">
    <skipped/>
  </testcase> <!-- loginUser -->
  <testcase classname="com.testNG.Program.Hard_Dependency_TestNG" name="CheckSavingAccountBalance" time="0.0">
    <skipped/>
  </testcase> <!-- CheckSavingAccountBalance -->
  <testcase classname="com.testNG.Program.Hard_Dependency_TestNG" name="CheckCurrentAccountBalance" time="0.0">
    <skipped/>
  </testcase> <!-- CheckCurrentAccountBalance -->
  <testcase classname="com.testNG.Program.Hard_Dependency_TestNG" name="logOut" time="0.0">
    <skipped/>
  </testcase> <!-- logOut -->
  <testcase classname="com.testNG.Program.Hard_Dependency_TestNG" name="closeApplication" time="0.003"/>
</testsuite> <!-- Default test -->
